### ISSUE TITLE
Minor typo (ture -> true)

### ISSUE THREAD

**Issue by kpapad904** [Hortenkommune/thinstation#1]
Minor typo ("ture" instead of "true") in line #52

https://github.com/Hortenkommune/thinstation/blob/c41f380c67b030ba8a566ae9be97b5dd1ad2f132/KIOSK_V/conf/build.conf#L52

**Comment by Forsbakk** [comment]
solved in https://github.com/Hortenkommune/thinstation/commit/39f2daad6f5f3bcdf96ac15c147b8df8a6f9dff5
